from setuptools import setup, find_packages

setup(
	name='basicsr',
	version='1.4.2',
	description='Open Source Image and Video Super-Resolution Toolbox',
	author='Xintao Wang',
	author_email='xintao.wang@outlook.com',
	keywords='computer vision, restoration, super resolution',
	url='https://github.com/xinntao/BasicSR',
	packages=find_packages(exclude=('options', 'datasets', 'experiments', 'results', 'tb_logger', 'wandb')),
	include_package_data=True,
	license='Apache License 2.0',
	classifiers=[
		'Development Status :: 4 - Beta',
		'License :: OSI Approved :: Apache Software License',
		'Operating System :: OS Independent',
		'Programming Language :: Python :: 3',
		'Programming Language :: Python :: 3.7',
		'Programming Language :: Python :: 3.8',
	],
	install_requires=[
		"addict",
		"future",
		"lmdb",
		"numpy>=1.17",
		"opencv-python",
		"Pillow",
		"pyyaml",
		"requests",
		"scikit-image",
		"scipy",
		"tb-nightly",
		"torch>=1.7",
		"torchvision",
		"tqdm",
		"yapf",
	],
)
